apiVersion: apps/v1
kind: Deployment
metadata:
  name: chip-shop-delpoyment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chip-shop-app
  template:
    metadata:
      labels:
        app: chip-shop-app
    spec:
      containers:
      - name: chip-shop-container
        image: miggarcia338/chip-shop:1
        ports:
        - containerPort: 8080
        env:
          - name: DB_URL
            value: jdbc:postgresql://database-1.cf6kctbmeuxl.us-east-2.rds.amazonaws.com:5432/postgres
          - name: DB_USER
            value: postgres
          - name: DB_PASS
            value: pa55w0rd
