apiVersion: apps/v1
kind: Deployment
metadata:
  name: chip-shop-delpoyment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chip-shop-app
  template:
    metadata:
      labels:
        app: chip-shop-app
    spec:
      containers:
      - name: chip-shop-container
        image: miggarcia338/chip-shop:1
        ports:
        - containerPort: 8080
        env:
          - name: DB_URL
            value: jdbc:postgresql://postgres-service:5432/postgres
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: pass
