spring:
  datasource:
    url: jdbc:postgresql://database-1.cf6kctbmeuxl.us-east-2.rds.amazonaws.com:5432/postgres #${DB_URL}
    username: postgres #${DB_USER}
    password: pa55w0rd #${DB_PASS}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate